# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# This is the main configuration file for the Cloud Frog Bot project.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

bot {
  token: ${BOT_TOKEN}
}

redis {
  uri: "redis://localhost:6379"
}

yandex-api {
  client-id: ${YANDEX_API_CLIENT_ID}
  client-secret: ${YANDEX_API_CLIENT_SECRET}
}
